# EDA

### Import neccesary lib and import raw data

In [1]:
import pandas as pd
from pathlib import Path

### Because the data file have 2 sheets so i merged into 1 dataframe

In [2]:
path = Path("../data/raw/online_retail_II.xlsx")
dict_of_df = pd.read_excel(path, sheet_name=None)
df_merged = pd.concat(dict_of_df.values(), ignore_index=True)

In [3]:
print(len(df_merged))

1067371

## Check info datasets

In [8]:
df_merged.shape

(1067371, 8)

In [4]:
df_merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

### Data Set Information:
This Online Retail II data set contains all the transactions occurring for a UK-based and registered, non-store online retail between 01/12/2009 and 09/12/2011.The company mainly sells unique all-occasion gift-ware. Many customers of the company are wholesalers.

Attribute Information:
- InvoiceNo: Invoice number. Nominal. A 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter 'c', it indicates a cancellation.

- StockCode: Product (item) code. Nominal. A 5-digit integral number uniquely assigned to each distinct product.

- Description: Product (item) name. Nominal.

- Quantity: The quantities of each product (item) per transaction. Numeric.

- InvoiceDate: Invice date and time. Numeric. The day and time when a transaction was generated.

- UnitPrice: Unit price. Numeric. Product price per unit in sterling (£).

- CustomerID: Customer number. Nominal. A 5-digit integral number uniquely assigned to each customer.

- Country: Country name. Nominal. The name of the country where a customer resides.

In [9]:
df_merged.head(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [11]:
df_merged.tail(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

## Categorical variable

### Country check

In [22]:
Country_check = df_merged['Country']
Country_check.unique()

<StringArray>
[      'United Kingdom',               'France',                  'USA',
              'Belgium',            'Australia',                 'EIRE',
              'Germany',             'Portugal',                'Japan',
              'Denmark',              'Nigeria',          'Netherlands',
               'Poland',                'Spain',      'Channel Islands',
                'Italy',               'Cyprus',               'Greece',
               'Norway',              'Austria',               'Sweden',
 'United Arab Emirates',              'Finland',          'Switzerland',
          'Unspecified',                'Malta',              'Bahrain',
                  'RSA',              'Bermuda',            'Hong Kong',
            'Singapore',             'Thailand',               'Israel',
            'Lithuania',          'West Indies',              'Lebanon',
                'Korea',               'Brazil',               'Canada',
              'Iceland',         'Saudi Arabia',       'Czech Republic',
   'European Community']
Length: 43, dtype: str

#### I found that there are some errors in the country name. For ex: EIRE mean Ireland, RSA mean Republic of South Africa, Unspecifed mean other countries. So i need to normalize the name of its

In [23]:
df_merged['Country'].value_counts()

Country
United Kingdom          981330
EIRE                     17866
Germany                  17624
France                   14330
Netherlands               5140
Spain                     3811
Switzerland               3189
Belgium                   3123
Portugal                  2620
Australia                 1913
Channel Islands           1664
Italy                     1534
Norway                    1455
Sweden                    1364
Cyprus                    1176
Finland                   1049
Austria                    938
Denmark                    817
Unspecified                756
Greece                     663
Japan                      582
USA                        535
Poland                     535
United Arab Emirates       500
Israel                     371
Hong Kong                  364
Singapore                  346
Malta                      299
Iceland                    253
Canada                     228
Lithuania                  189
RSA                        169
Bahrain                    126
Brazil                      94
Thailand                    76
Korea                       63
European Community          61
Lebanon                     58
West Indies                 54
Bermuda                     34
Nigeria                     32
Czech Republic              30
Saudi Arabia                10
Name: count, dtype: int64

#### There are about 43 countries in this datasets. And leading of the total transactions is in UK.

### Customer

In [30]:
Customer_check = df_merged['Customer ID']
print(Customer_check.nunique())

5942

#### About 5942 distinct customers, but excluding missing values.

In [32]:
Customer_check.value_counts().head(10)

Customer ID
17841.0    13097
14911.0    11613
12748.0     7307
14606.0     6709
14096.0     5128
15311.0     4717
14156.0     4130
14646.0     3890
13089.0     3438
16549.0     3255
Name: count, dtype: int64

#### Top 10 customers by number of transactions (frequency)

### Product check

In [31]:
Product_check = df_merged['StockCode']
print(Product_check.nunique())

5305

#### About 5305 products in this dataset.

In [42]:
Product_check.value_counts().head(10)

StockCode
85123A    5829
22423     4424
85099B    4216
21212     3318
20725     3259
84879     2960
47566     2768
21232     2747
22197     2549
22383     2540
Name: count, dtype: int64

#### Top 10 products with most sales

## Time span analysis

In [44]:
df_merged['InvoiceDate'].min()

Timestamp('2009-12-01 07:45:00')

In [45]:
df_merged['InvoiceDate'].max()

Timestamp('2011-12-09 12:50:00')

### So the datasets have a duration from Jan 2009 to Dec 2011

## Descriptive statistics

In [49]:
df_merged.describe().round(2)

          Quantity                 InvoiceDate        Price  Customer ID
count 1,067,371.00                     1067371 1,067,371.00   824,364.00
mean          9.94  2011-01-02 21:13:55.394029         4.65    15,324.64
min     -80,995.00         2009-12-01 07:45:00   -53,594.36    12,346.00
25%           1.00         2010-07-09 09:46:00         1.25    13,975.00
50%           3.00         2010-12-07 15:28:00         2.10    15,255.00
75%          10.00         2011-07-22 10:23:00         4.15    16,797.00
max      80,995.00         2011-12-09 12:50:00    38,970.00    18,287.00
std         172.71                         NaN       123.55     1,697.46

- The dataset shows strong right-skewness in both Quantity and Price, with most transactions involving small quantities and low-priced items
- Extreme values are present, including negative quantities and prices, indicating returns, cancellations, or data errors
- High standard deviation confirms significant variability and the presence of outliers
- The majority of transactions are small-scale, suggesting typical retail purchasing behavior